name: Deploy Spring Boot to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t my-spring-app .

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" \
             | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag my-spring-app ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/toy4-spring:latest
            docker stop spring-container || true
            docker rm spring-container || true
            docker run -d --name spring-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/toy4-spring:latest
